// src/ui/components/code-editor/actions/components/fix/index.vue
<script setup lang="ts">
import {
  Modal,
  ModalContent,
  ModalTitle,
  ModalTrigger,
  ModalClose,
} from "../../../../modal";

import { button } from "../../../../../../../styled-system/recipes";

import { choose_container, choose_wrapper, choices } from "./styles";

import { handleConvertFile } from "../../../../../../lib/handlers";

import appState from "../../../../../../states";

import MdiWrenchOutline from "../../../../icons/mdi-wrench-outline.vue";

import Tooltip from "../../../../tooltip/index.vue";

function handleDefault() {
  handleConvertFile(appState.activeFile!);
}

function handleContinue() {
  //todo
}
</script>

<template>
  <Modal>
    <Tooltip content="Convert/Fix" side="bottom">
      <ModalTrigger as-child>
        <button
          :class="button({ visual: 'square' })"
          :style="{
            pointerEvents: appState.activeFile?.name ? 'auto' : 'none',
          }"
        >
          <MdiWrenchOutline />
        </button>
      </ModalTrigger>
    </Tooltip>
    <ModalContent>
      <ModalTitle>Convert file</ModalTitle>
      <div>
        <p>You are about to convert "{{ appState.activeFile?.name }}".</p>
        <p>How to proceed?</p>
        <p>Default settings or continue to set up the file yourself.</p>
      </div>
      <div :class="choose_container">
        <div :class="choose_wrapper">
          <div :class="choices">
            <ModalClose as-child>
              <button
                :class="button({ visual: 'dialog' })"
                @click="handleDefault"
              >
                Default
              </button>
            </ModalClose>
            <ModalClose as-child>
              <button
                :class="button({ visual: 'dialog' })"
                @click="handleContinue"
              >
                Continue
              </button>
            </ModalClose>
          </div>
          <ModalClose as-child>
            <button :class="button({ visual: 'dialog' })">Cancel</button>
          </ModalClose>
        </div>
      </div>
    </ModalContent>
  </Modal>
</template>

// src/components/FileHandlingSection/components/handlers/Fix.tsx
import { DefaultButton } from "@/components/Globals/DefaultButton";
import { Wrench } from "@/components/Globals/Icons";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/Globals/Tooltip";
import {
  Modal,
  ModalClose,
  ModalContent,
  ModalTitle,
  ModalTrigger,
} from "@/components/Globals/Modal";

import { useAppSelector } from "@/redux/hooks";

import { handleConvertFiles } from "@/lib/handlers";

export default function Fix() {
  const active = useAppSelector((state) => state.app.activeFile);

  function handleDefaultSettings() {
    handleConvertFiles([active!], [active!.id]);
  }

  return (
    <Modal>
      <TooltipProvider delayDuration={250}>
        <Tooltip>
          <TooltipTrigger asChild>
            <ModalTrigger asChild>
              <DefaultButton disabled={active ? false : true} size="icon">
                <Wrench />
              </DefaultButton>
            </ModalTrigger>
          </TooltipTrigger>
          <TooltipContent className="right-2.5">Convert</TooltipContent>
        </Tooltip>
      </TooltipProvider>
      {/* Modal content */}
      <ModalContent>
        <ModalTitle>Convert files</ModalTitle>
        <div className="pointer-events-none">
          <p>You are about to convert 1 file.</p>
          <p>You can use the default settings or set the settings yourself.</p>
          <p className="my-2">How do you want to proceed?</p>
        </div>
        <div className="flex flex-row justify-between space-x-2 relative top-5">
          <ModalClose asChild>
            <DefaultButton onClick={handleDefaultSettings}>
              Use default settings
            </DefaultButton>
          </ModalClose>
          <ModalClose asChild>
            <DefaultButton>Continue</DefaultButton>
          </ModalClose>
        </div>
      </ModalContent>
    </Modal>
  );
}
