// src/ui/compounds/code-editor/actions/components/fix/index.vue
<script setup lang="ts">
import {
  Modal,
  ModalContent,
  ModalTitle,
  ModalTrigger,
  ModalClose,
} from "~/ui/primitives/modal";

import { button } from "~/styled-system/recipes";

import { choose_container, choose_wrapper, choices } from "./styles";

import { handleConvertFile } from "~/lib/handlers";

import { fm, mm } from "~/stores/index";

import MdiWrenchOutline from "~/ui/primitives/icons/mdi-wrench-outline.vue";

import Tooltip from "~/ui/primitives/tooltip/index.vue";

function handleDefault() {
  if (fm.active) {
    handleConvertFile(fm.active);
  }
}
</script>

<template>
  <Modal>
    <Tooltip content="Convert/Fix" side="bottom">
      <ModalTrigger as-child>
        <button
          :class="button({ visual: 'square' })"
          :style="{
            pointerEvents:
              fm.active && fm.active.type === 'CONV_TROYBIN' ? 'auto' : 'none',
          }"
        >
          <MdiWrenchOutline />
        </button>
      </ModalTrigger>
    </Tooltip>
    <ModalContent>
      <ModalTitle>Convert file</ModalTitle>
      <div>
        <p>You are about to convert "{{ fm.active?.name }}".</p>
        <p>How to proceed?</p>
        <p>Default settings or continue to set up the file yourself.</p>
      </div>
      <div :class="choose_container">
        <div :class="choose_wrapper">
          <div :class="choices">
            <ModalClose as-child>
              <button
                :class="button({ visual: 'dialog' })"
                @click="handleDefault"
              >
                Default
              </button>
            </ModalClose>
            <ModalClose as-child>
              <button
                :class="button({ visual: 'dialog' })"
                @click="mm.openSettings(true, 'single')"
              >
                Continue
              </button>
            </ModalClose>
          </div>
          <ModalClose as-child>
            <button :class="button({ visual: 'dialog' })">Cancel</button>
          </ModalClose>
        </div>
      </div>
    </ModalContent>
  </Modal>
</template>

// src/components/FileHandlingSection/components/handlers/Fix.tsx
import { DefaultButton } from "@/components/Globals/DefaultButton";
import { Wrench } from "@/components/Globals/Icons";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/Globals/Tooltip";
import {
  Modal,
  ModalClose,
  ModalContent,
  ModalTitle,
  ModalTrigger,
} from "@/components/Globals/Modal";

import { useAppSelector, useAppDispatch } from "@/redux/hooks";
import { continueModal } from "@/redux/reducers/appSlice";

import { handleConvertFiles } from "@/lib/handlers";

export default function Fix() {
  const active = useAppSelector((state) => state.app.activeFile);

  const dispatch = useAppDispatch();

  function handleDefaultSettings() {
    handleConvertFiles([active!], [active!.id]);
  }

  return (
    <>
      <Modal>
        <TooltipProvider delayDuration={250}>
          <Tooltip>
            <TooltipTrigger asChild>
              <ModalTrigger asChild>
                <DefaultButton
                  disabled={
                    active && active.type === "CONV_TROYBIN" ? false : true
                  }
                  size="icon"
                >
                  <Wrench />
                </DefaultButton>
              </ModalTrigger>
            </TooltipTrigger>
            <TooltipContent className="right-2.5">Convert</TooltipContent>
          </Tooltip>
        </TooltipProvider>
        {/* Modal content */}
        <ModalContent>
          <ModalTitle>Convert files</ModalTitle>
          <div className="pointer-events-none">
            <p>You are about to convert 1 file.</p>
            <p>
              You can use the default settings or set the settings yourself.
            </p>
            <p className="my-2">How do you want to proceed?</p>
          </div>
          <div className="flex flex-row justify-between space-x-2 relative top-5">
            <ModalClose asChild>
              <DefaultButton onClick={handleDefaultSettings}>
                Use default settings
              </DefaultButton>
            </ModalClose>
            <ModalClose asChild>
              <DefaultButton
                onClick={() =>
                  dispatch(continueModal({ show: true, method: "single" }))
                }
              >
                Continue
              </DefaultButton>
            </ModalClose>
          </div>
        </ModalContent>
      </Modal>
    </>
  );
}
